<?php
include_once(__DIR__ . DIRECTORY_SEPARATOR . 'PadOptSubmodule.interface');

error_reporting(E_ALL);
ini_set('display_errors', '1');

class PadOptLiveCustomizers extends WireData implements PadOptSubmodule, Module {
  protected $input_prefix = 'live_';
  protected $img_path = 'files/padopt_livecustomizers/';
  protected $img_default = 'default.png';
  protected $class_maindiv = 'padopt-livecustomizer';
  protected $class_viewport = 'padopt-livecustomizer-viewport';
  protected $id_prefix = 'padoptlc-';
  protected $viewport_width;
  protected $viewport_height;
  protected $padopt;

  public static function getModuleInfo() {
    return array(
      'title' => 'PadLoper Client Live Customizers',
      'version' => 1,
      'summary' => 'Add client graphical customizers to change Padloper product options, with a live rendering',
      'icon' => 'cubes',
      'href' => 'https://github.com/jvaubourg/processwire-module-padopt',
      'author' => 'Julien Vaubourg',
      'singular' => true,
      'autoload' => true,
      'requires' => 'PadOpt',
    );
  }

  public function init() {
    $this->padopt = $this->modules->get('PadOpt');
    $this->padopt->registerSubmodule($this);

    $this->addHookAfter('Page::render', $this, 'addScriptsAndStyles');
  }

  private function setViewportInfos($inputfields) {
    $inputfield_name = $inputfields[0]->name;

    $this->viewport_name = preg_replace("/^{$this->padopt->getGeneralInputPrefix()}{$this->input_prefix}([a-z0-9]+)_.*$/i", '$1', $inputfield_name);

    $viewport_size = getimagesize("../{$this->img_path}/{$this->viewport_name}/{$this->img_default}");
    $this->viewport_width = $viewport_size[0];
    $this->viewport_height = $viewport_size[1];
  }

  // after Page::render
  public function addScriptsAndStyles($event) {
    $page = $event->object; 
    $module_url = $this->config->urls->siteModules . basename(__DIR__);
    
    if($page->template->fields->get($this->padopt->getFieldTplName())) {
      $scripts = <<<EOT
        <script>
          const padoptlc_inputprefix = '{$this->padopt->getGeneralInputPrefix()}{$this->input_prefix}';
          const padoptlc_classviewport = '{$this->class_viewport}';
          const padoptlc_classmaindiv = '{$this->class_maindiv}';
          const padoptlc_idprefix = '{$this->id_prefix}';
          const padoptlc_imgurl = '{$this->urls->site}{$this->img_path}';
        </script>
EOT;
      $styles = <<<EOT
        <style>
          .{$this->class_viewport} {
            background-image: url({$this->urls->site}{$this->img_path}{$this->viewport_name}/{$this->img_default});
          }
          .{$this->class_viewport}, .{$this->class_viewport} div {
            width: {$this->viewport_width}px;
            height: {$this->viewport_height}px;
          }
        </style>
EOT;
      $scripts .= "<script type='text/javascript' src='{$module_url}/templates/scripts/padopt_livecustomizers.js'></script>";
      $styles .= "<link type='text/css' href='{$module_url}/templates/styles/padopt_livecustomizers.css' rel='stylesheet' />";

      $event->return = str_replace('</head>', "{$styles}{$scripts}</head>", $event->return); 
    }
  }

  public function getInputPrefix() {
    return $this->input_prefix;
  }

  public function render($inputfields) {
    $form = $this->modules->get('InputfieldForm');

    $this->setViewportInfos($inputfields);

    $render = "<div class='{$this->class_maindiv}'>";
    $render .= "<div class='{$this->class_viewport}'>";
    
    foreach($inputfields as $inputfield) {
      $render .= "<div id='{$this->id_prefix}{$inputfield->name}'>";
      $form->add($inputfield);
    }
  
    foreach($inputfields as $inputfield) {
      $render .= '</div>';
    }

    $render .= '</div>';
    $render .= preg_replace('/<\/?form[^>]*>/', '', $form->render());
    $render .= '</div>';

    return $render;
  }
}
